# Generated by Django 4.2 on 2026-03-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0004_cashflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='type_color',
            field=models.CharField(choices=[('income', 'Пополнение'), ('expense', 'Списание'), ('other', 'Другое')], default='expense', max_length=10, verbose_name='Тип операции'),
        ),
    ]
